### ISSUE TITLE
Testing code using EventProcessorHost

### ISSUE THREAD

**Issue by fredxfred** [Azure/azure-event-hubs-java#433] opened 2019-03-05 01:53 UTC
## Actual Behavior
1. You must connect your code using EventProcessorHost to a real EventHub even for testing
2. This requires operational overhead and makes testing of EventHub-receiving code time consuming

## Expected Behavior
1. There is some testing library we can use to locally emulate the connection between EventProcessorHost and an EventHub/storage account.

It would be really nice to be able to be able to somehow locally emulate an eventhub so that I can test my code using Azure EventHubs locally. Currently, the only way I can fathom to run tests (short of trying to reverse engineer backend logic) is to provision special test resources and write separate code to handle populating those resources with data, which is much more time consuming and complicated than it needs to be. With Kafka, you can create a "cluster" locally, which is very convenient compared to the testing story with Event Hubs.

**Comment by fredxfred** [comment] 2019-03-06 21:20
For example, it would be nice if at least we could create EventData objects with user defined SystemProperties in an easy way.

**Comment by JamesBirdsall** [comment] 2019-03-07 21:12
We are aware of the issue. Getting proper mocking in place would make our own testing easier and better, too. The problem is that it's a big work item with only indirect benefits, so it's hard to get on the schedule.

Regarding the specific request to make EventData completely creatable, that is a small enough change that I can probably sneak it into the next release.

**Comment by fredxfred** [comment] 2019-03-07 22:01
Awesome, thank you!

**Comment by JamesBirdsall** [comment] 2019-03-08 02:46
@fredxfred See PR #435 -- we already made this change in some of our other SDKs so there should be no issue getting it in here.

**Comment by JamesBirdsall** [comment] 2019-04-09 00:22
EventData change released in 2.3.0.

**Closed by JamesBirdsall** 2019-04-09 00:22 UTC

**Comment by vivin-kr** [comment] 2021-06-23 14:56
I would like to vote for this issue as well. This would really help during integration testing.

**Comment by vivin** [comment] 2021-06-23 14:58
I would like to vote for this as well. Are there any updates on providing a local/embedded event hub we could use for integration testing?

**Comment by JamesBirdsall** [comment] 2021-06-23 16:28
This client is now legacy and deprecated. We will still be making fixes for issues that impact customers in production but we won't be investing in new feature work. The new Java client is at https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/eventhubs/azure-messaging-eventhubs -- opening an issue there with the "Event Hubs" tag will get the attention of the right people.

**Comment by vivin** [comment] 2021-06-24 14:22
Thank you @JamesBirdsall! I will open one there.
