### ISSUE TITLE
EPH crashes due to high memory usage by large number of threads

### ISSUE THREAD

**Issue by jtaubensee** [Azure/azure-event-hubs-java#19] opened 2016-11-01 15:13 UTC
_From @serkantkaraca on July 18, 2016 18:46_

EPH client process memory usage hit almost 3GB and then process crashed due to not able to allocate more resources. Attached screenshot shows the memory footprint during the run.

<2790868.22> 07/18/2016 18:24:16 - Error: JAVA-Receiver_1<stderr>: Java HotSpot(TM) 64-Bit Server VM warning: Attempt to allocate stack guard pages failed.
<2790868.22> 07/18/2016 18:24:16 - Error: JAVA-Receiver_1<stderr>: Java HotSpot(TM) 64-Bit Server VM warning: Attempt to allocate stack guard pages failed.
<2790868.22> 07/18/2016 18:24:16 - Error: JAVA-Receiver_1<stderr>: Java HotSpot(TM) 64-Bit Server VM warning: Attempt to unguard stack red zone failed.
<2790868.22> 07/18/2016 18:24:16 - Error: JAVA-Receiver_1<stderr>: Java HotSpot(TM) 64-Bit Server VM warning: Attempt to allocate stack guard pages failed.
<2790868.22> 07/18/2016 18:24:16 - Error: JAVA-Receiver_1<stderr>: Java HotSpot(TM) 64-Bit Server VM warning: Attempt to unguard stack red zone failed.
<2790868.22> 07/18/2016 18:24:16 - Error: JAVA-Receiver_1<stderr>: Java HotSpot(TM) 64-Bit Server VM warning: Attempt to unguard stack red zone failed.

![capture](https://cloud.githubusercontent.com/assets/16924470/16926315/fbccd7f8-4cdc-11e6-978f-fd204468eced.PNG)

_Copied from original issue: Azure/azure-event-hubs#192_

**Comment by jtaubensee** [comment] 2016-11-01 15:13
_From @sjkwak on October 28, 2016 18:55_

#283

**Comment by sjkwak** [comment] 2016-11-04 18:58
The issue is fixed in version 0.9.0

**Closed by sjkwak** 2016-11-04 18:58 UTC
Labels: EventProcessorHost
