### ISSUE TITLE
Leaking proton reactor threads on MessagingFactory timeout

### ISSUE THREAD

**Issue by yarinm** [Azure/azure-event-hubs-java#380] opened 2018-09-20 01:29 UTC
## Actual Behavior
1. We're getting from time to time the following from (usually a surge of exceptions like this over the course of a few minutes)
java.util.concurrent.CompletionException: com.microsoft.azure.servicebus.TimeoutException: Opening MessagingFactory timed out.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at com.microsoft.azure.servicebus.MessagingFactory$3.run(MessagingFactory.java:200)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.azure.servicebus.TimeoutException: Opening MessagingFactory timed out.
	... 8 common frames omitted

And it seems that proton reactor threads aren't clean properly and we see 4x the times of the exception threads dangling:

Example for such thread:
"Thread-38381" #162995 prio=5 daemon=false alive=true interrupted=false os_prio= tid= nid=
 runnable []
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.qpid.proton.reactor.impl.SelectorImpl.select(SelectorImpl.java:126)
        at org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:57)
        at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:381)
        at org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87
)
        at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206)
        at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:309)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:277)
        at com.microsoft.azure.servicebus.MessagingFactory$RunReactor.run(MessagingFactory.java:383)
        at java.lang.Thread.run(Thread.java:745)

## Versions  
- Ubuntu 14.04:
- 0.14.5

**Comment by SreeramGarlapati** [comment] 2018-09-20 02:49
@yarinm - this issue was fixed a while back in this PR #192.

**Comment by SreeramGarlapati** [comment] 2018-09-20 22:48
please re-open if you feel the need. closing now as it is already fixed in latest versions.

**Comment by yarinm** [comment] 2018-09-21 19:36
@SreeramGarlapati  did you even look at when this is happening? I know the fix #192 I've even backported it to 0.14.5 version a while back. It's only relevant when it's happening when creating a new connection. My issue is happening during other operations (send / receive / create receiver / create sender).

These timeouts usually happen when we are getting throttled from EHs due to high load on our end.

**Comment by SreeramGarlapati** [comment] 2018-09-21 20:32
This is very strange @yarinm! Your exception stacktrace shows the problem is with messaging factory open:
```
java.util.concurrent.CompletionException: com.microsoft.azure.servicebus.TimeoutException: Opening MessagingFactory timed out.
```
Per our design, this cannot happen while sending and receiving - as this is used to create `EventHubClient` instance, which inturn is used to create the Sender and Receiver objects.

How did you hit this error while sending and receiving? Did you fork our library & make any custom changes and are hitting this error?

Appreciate, if you can upgrade to our latest version (`1.2.0`) - to optimize both of our time not reinventing old issues.

**Comment by sjkwak** [comment] 2019-01-16 03:44
Please reopen it if this still happens in the latest release (version 2.2).

**Closed by sjkwak** 2019-01-16 03:44 UTC
