### ISSUE TITLE
Supporting GetRuntimeInformationAsync in Java

### ISSUE THREAD

**Issue by lhaiesp** [Azure/azure-event-hubs-java#54] opened 2017-02-14 16:26 UTC
Right now the java client library doesn't provide the information about count of partitions for a specific EventHub entity. For our use case, this is very important. We would like to have something similar to the GetRuntimeInformationAsync() in C#:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.eventhubclient#Microsoft_Azure_EventHubs_EventHubClient_GetRuntimeInformationAsync

Or let me know if there is other way to obtain the number of partitions in the java library.

Thanks,
Hai

**Comment by SreeramGarlapati** [comment] 2017-02-16 23:23
@lhaiesp - we have a plan to deliver this API soon - don't have an exact ETA yet. however, here are the 2 ways you can achieve the equivalent of this API:
1) https://github.com/Azure/azure-event-hubs-java/blob/master/azure-eventhubs/src/test/java/com/microsoft/azure/eventhubs/sendrecv/RequestResponseTest.java
2) https://github.com/Azure/azure-event-hubs-java/blob/master/azure-eventhubs-eph/src/main/java/com/microsoft/azure/eventprocessorhost/PartitionManager.java#L63

**Comment by lhaiesp** [comment] 2017-02-18 01:29
Hi, I don't need this right away. But I would like to know exactly what you implied by saying "deliver this API soon". I don't need a commitment, but some approximate ETA would work.

If this could come within a few months I would be happy to wait

**Comment by jtaubensee** [comment] 2017-02-24 01:02
This is a duplicate of #14

**Closed by jtaubensee** 2017-02-24 01:02 UTC
Labels: duplicate
