### ISSUE TITLE
EPH cannot recover under multiple instances deployment

### ISSUE THREAD

**Issue by nevinchen** [Azure/azure-event-hubs-java#432] opened 2019-02-27 03:31 UTC
## Actual Behavior
1. Start two EPH clients, which belong to the same consumer group. Each of them will consume 50% of the partitions.
2. Terminate the network connection of one EPH client for more than 30 seconds. The other one will take over all the partitions, which is as expected.
3. Recover the network connection of the first EPH client. 
4. The first EPH client cannot connect to any of the partition anymore until restarts.

## Expected Behavior
1. After network connection recovers, the first EPH client should be able to take over half of the partitions as beginning.

## Versions  
- OS platform and version: Ubuntu / 16.04 & Windows 10
- Maven package version or commit ID:  azure-eventhubs-eph 2.4.0

## Root Cause Analysis
The EPH lost the leases because of higher epoch acquired by other clients. However, when connection recovers, it is expected to re-acquire half of the partitions to rebalance the workload between consumers in the same consume group. The rebalancing doesn't work after re-connection. According to the code snippet below, the connection lost will lead the first scan method to throw an exception and the timer task for rebalancing terminates. It would be better to keep the rebalancing thread always be scheduled.

![default](https://user-images.githubusercontent.com/9671875/53463181-3243b100-3a81-11e9-9951-a9d438640296.png)

**Comment by JamesBirdsall** [comment] 2019-03-02 02:03
Thank you for the detailed repro steps. I will give them a try next week.

It absolutely is the intention that the partition scanner should always be rescheduled! whenCompleteAsync() is used here specifically because it will execute even if scan() completes exceptionally, and there's nothing in scan that should throw directly instead of via exceptional completion. I will be interested to see what happens when I try this.

**Comment by JamesBirdsall** [comment] 2019-03-04 23:25
I have reproduced the issue and am investigating. I will update here with what I find.

Thank you for reporting this!

**Comment by fredxfred** [comment] 2019-03-05 02:04
Hi, random stranger chiming in, but this to me seems to be expected behavior.  When the first client closed, it lost its leases on the partitions it was consuming, and the second client gained leases on those partitions. The second client now has leases on all partitions. The first client shouldn't be able to regain leases until the second client relinquishes any of its leases. 

This is as expected: if the first client were able to regain leases without the second client's leases expiring, the system could enter a state where the first client loses a lease on a partition before it has the opportunity to commit that it has received data, resulting in double-reads within a consumer group on that partition (for example, in code I have written for a class EventProcessor implementing IEventProcessor, I do not commit in onData until the EventProcessor can read a signal emitted by a background thread indicating that the data read from that partition up to a certain event is ready to commit). But, perhaps I am either misusing IEventProcessor or do not understand your problem.

**Comment by JamesBirdsall** [comment] 2019-03-05 02:11
Hello! No, this is not expected behavior. If you look through the code in PartitionScanner, you will find mentions of lease stealing: if the host instances are imbalanced, then instances with fewer than the desired number of partitions can forcibly take over partitions from other instances. As with any time partitions move between host instances, this can cause events to be reprocessed, the exact number depending on the timing and how often the application checkpoints. It's something the application developer needs to be aware of.

**Comment by fredxfred** [comment] 2019-03-05 02:22
Oh, my bad then, I guess I can't assume that data won't be double counted when using EventProcessorHost then. Thanks!

**Comment by JamesBirdsall** [comment] 2019-03-08 01:18
See PR #434 for the fix.

@nevinchen Your analysis was correct. The StorageExceptions that we expected were getting wrapped in another exception type which was not caught anywhere and was killing the scanning thread before it could reschedule itself.

**Comment by JamesBirdsall** [comment] 2019-04-09 00:21
Fix released in EPH 2.5.0.

**Closed by JamesBirdsall** 2019-04-09 00:21 UTC
