### ISSUE TITLE
Publish snapshot builds into sonatype

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-event-hubs-java#253] opened 2018-02-13 20:21 UTC
I suspect this is a similar issue to https://github.com/Azure/azure-libraries-for-java/issues/171 - when trying to run `mvn javadoc:javadoc` on the azure-event-hubs-java repo, it fails because snapshot dependencies aren't able to be satisfied (because they aren't published publicly). The error is:

> [ERROR] Failed to execute goal on project azure-eventhubs-eph: Could not resolve dependencies for project com.microsoft.azure:azure-eventhubs-eph:jar:1.0.0-SNAPSHOT: Could not find artifact com.microsoft.azure:azure-eventhubs:jar:1.0.0-SNAPSHOT -> [Help 1]

I suspect you need to do similar to the related pull request https://github.com/Azure/azure-libraries-for-java/pull/175/files - if this could be done then we can automatically generate your JavaDoc in my https://github.com/JonathanGiles/azure-javadocs project.

**Comment by SreeramGarlapati** [comment] 2018-02-23 19:13
HI @JonathanGiles,
I believe the goal of your `mvn Javadoc:javadoc` project - is to generate docs for the **released** builds - if so, please point to our `master` branch. We keep our `master` branch - same as what we release - and `dev` branch is where we actively develop. 

However, all the feedback - that you provided is incorporated only in the current release window - which will be released by end of Feb. 
So, right now, if you point to our `master` branch - there might be some build warning etc.
I believe once we release current bits and you start running your automated system against our `master` branch - this problem should be solved.

**Comment by SreeramGarlapati** [comment] 2018-03-02 16:52
HI @JonathanGiles, our `master` branch now is set to `1.0.0` - which doesn't have references to SNAPSHOT versions and `mvn javadoc:javadoc` runs without any errors.

**Comment by SreeramGarlapati** [comment] 2018-03-15 19:32
HI @JonathanGiles, I believe the issue is fixed now - as I did not hear back from you and since the issue is open for a while - I am closing this - please re-open if you feel the need.
Thanks a lot for making the docs story better!

**Closed by SreeramGarlapati** 2018-03-15 19:32 UTC
